### ISSUE TITLE
TMP_SDFShaderGUI_Dissolve has compile errors in TMPro 1.3.0

### ISSUE THREAD

**Issue by martinpi** [mob-sakai/DissolveEffectForTMPro#8]
**Describe the bug**
Compile errors

**To Reproduce**
Just open it in the above version.

I've fixed the error and attached the file with the fix. Seems like TMPro doesn't have a MaterialPanel class anymore.

Sorry for not filing a pull request – I've never done that :)

Thanks for this nice project!

[TMP_SDFShaderGUI_Dissolve.cs.zip](https://github.com/mob-sakai/DissolveEffectForTMPro/files/2919866/TMP_SDFShaderGUI_Dissolve.cs.zip)

**Comment by mob-sakai** [comment]
Hi @martinpi 
Thank you for reporting!
